# Generated by Django 5.2.17 on 2026-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='圖片')),
                ('link', models.URLField(blank=True, default='', verbose_name='連結')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '廣告橫幅',
                'verbose_name_plural': '廣告橫幅',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Lalainluv', max_length=100, verbose_name='網站名稱')),
                ('line_url', models.URLField(blank=True, default='', verbose_name='LINE 連結')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram 連結')),
                ('gmail', models.EmailField(blank=True, default='', max_length=254, verbose_name='Gmail 信箱')),
                ('about_us', models.TextField(blank=True, default='', verbose_name='關於我們')),
                ('notice', models.TextField(blank=True, default='', verbose_name='注意事項')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
    ]
