# Generated by Django 5.2.17 on 2026-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='逛逛拉拉熊選物', max_length=40, verbose_name='按鈕文字'),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='手機版圖片（選填）'),
        ),
    ]
