# Generated by Django 5.2.17 on 2026-09-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='Session Key')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '購物車項目',
                'verbose_name_plural': '購物車項目',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='訂單編號')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='總金額')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='收件人電話')),
                ('recipient_address', models.TextField(verbose_name='收件地址')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='單價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='訂單')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
            },
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_type', models.CharField(choices=[('japan_connect', '日本連線'), ('custom', '客制需求'), ('product_wish', '商品許願')], max_length=20, verbose_name='許願類型')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(verbose_name='詳細說明')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='wishes/', verbose_name='參考圖片')),
                ('reference_url', models.URLField(blank=True, default='', verbose_name='參考連結')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('reviewing', '評估中'), ('quoted', '已報價'), ('completed', '已完成'), ('rejected', '無法處理')], default='pending', max_length=20, verbose_name='狀態')),
                ('admin_reply', models.TextField(blank=True, default='', verbose_name='管理員回覆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '許願',
                'verbose_name_plural': '許願',
                'ordering': ['-created_at'],
            },
        ),
    ]
