# Generated by Django 5.2.17 on 2026-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='運費'),
        ),
    ]
