# Generated by Django 5.2.17 on 2026-09-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='網址代碼')),
                ('category_type', models.CharField(choices=[('hot_sale', '現正熱賣'), ('wish_pool', '許願池')], default='hot_sale', max_length=20, verbose_name='分類類型')),
                ('description', models.TextField(blank=True, default='', verbose_name='分類說明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='網址代碼')),
                ('description', models.TextField(blank=True, default='', verbose_name='商品說明')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='售價')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='原價')),
                ('image', models.ImageField(upload_to='products/', verbose_name='主圖')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='庫存')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='熱賣')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='圖片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品圖片',
                'verbose_name_plural': '商品圖片',
                'ordering': ['order'],
            },
        ),
    ]
